// OpenFlow — client config.
//
// Both values below are meant to be public. The Supabase publishable key can
// only do what your row-level security policies allow, and the resolver
// function hands back an owner ID and nothing else.
//
// Your four provider keys never appear here. They stay on your phone.

window.OPENFLOW = {
  // The live tunnel. Change this one line if the URL ever moves — every
  // sample on the site reads from here, so nothing else needs editing.
  api: "https://api-openflow.serveousercontent.com",

  supabaseUrl: "https://lellmqmqxkbiypwqbcej.supabase.co",
  supabaseKey: "sb_publishable_a6hALlGUrAM3GtbyO86cKw_fC5l71ah",

  // The model list below is the site's source of truth — the gateway is never
  // asked which models exist. Limits are PER ACCOUNT: the figure shown is what
  // each signed-in user gets, not a pool anyone shares. Set this to false and
  // the site stops contacting the gateway entirely, becoming fully static.
  liveCapacity: true,
  // --- models: generated by sitemodels.py from models.json
  models: [
    { id: "minimaxai/minimax-m3", provider: "NVIDIA", limit: "10/m", blurb: "MiniMax M3." },
    { id: "nvidia/nemotron-3-ultra-550b-a55b", provider: "NVIDIA", limit: "6/m", blurb: "550B total, 55B active. The heaviest here — tightest allowance to match." },
    { id: "nvidia/nemotron-3-nano-30b-a3b", provider: "NVIDIA", limit: "30/m", blurb: "30B total, 3B active. The light end of the Nemotron 3 line." },
    { id: "google/diffusiongemma-26b-a4b-it", provider: "NVIDIA", limit: "20/m", blurb: "26B total, 4B active." },
    { id: "mistral-large-latest", provider: "Mistral", limit: "1/s", blurb: "Mistral's flagship. One call a second, each." },
    { id: "mistral-small-latest", provider: "Mistral", limit: "1/s", blurb: "Cheap and quick for everyday prompts." },
    { id: "mistral-medium-latest", provider: "Mistral", limit: "1/s", blurb: "Between large and small." },
    { id: "gemma-4-31b-it", provider: "Google (Gemma)", limit: "30/m", blurb: "Gemma 4, 31B. This key serves Gemma only." },
    { id: "poolside/laguna-xs-2.1", provider: "Poolside", limit: "40/m", blurb: "Laguna XS, on Poolside's own endpoint — not sharing a key with anything else." },
    { id: "claude-haiku-4-5-20251001", provider: "ccproxy", limit: "20/m", blurb: "Haiku 4.5 via ccproxy. The only model exposed from that side." },
    { id: "google/google-paligemma", provider: "NVIDIA", limit: "30/m", blurb: "Sees images. Also the describer — send a picture to any text-only model here and this one writes what's in it first." },
    { id: "mistralai/mistral-nemotron", provider: "NVIDIA", limit: "20/m", blurb: "Mistral weights, NVIDIA's tuning." },
    { id: "treyleo16/llama4:31b", provider: "Ollama", limit: "6/m", blurb: "31B, running locally. Slow to answer, so requests queue rather than bounce." },
    { id: "treyleo16/trai-4-zynr-super-lightweight", provider: "Ollama", limit: "60/m", blurb: "Lightweight local model. Quickest thing on the list." },
    { id: "gpt-oss:120b-cloud", provider: "Ollama", limit: "10/m", blurb: "Open-weight 120B, run on Ollama Cloud rather than this machine." },
    { id: "gpt-oss:20b-cloud", provider: "Ollama", limit: "20/m", blurb: "The 20B sibling. Quicker, still off-device." },
    { id: "north-mini-code-1-0", provider: "Cohere", limit: "15/m", blurb: "Cohere North Mini, tuned for code." },
    { id: "glm-5.2-free", provider: "AiHubMix", limit: "10/m", blurb: "GLM 5.2." },
    { id: "coding-glm-5.2-free", provider: "AiHubMix", limit: "10/m", blurb: "GLM 5.2 tuned for code." },
    { id: "coding-kimi-k3-free", provider: "AiHubMix", limit: "10/m", blurb: "Kimi K3 tuned for code." },
    { id: "gemini-3.7-flash-free", provider: "AiHubMix", limit: "15/m", blurb: "Gemini 3.7 Flash. Sees images." },
    { id: "gemini-3.6-flash-free", provider: "AiHubMix", limit: "15/m", blurb: "Gemini 3.6 Flash. Sees images." },
    { id: "gemini-3.5-flash-lite-free", provider: "AiHubMix", limit: "30/m", blurb: "The lite tier — quickest of the Geminis." },
    { id: "nemotron-3.5-lightning-free", provider: "AiHubMix", limit: "20/m", blurb: "NVIDIA's Lightning tier, built for speed." },
    { id: "dots-3-note-preview-free", provider: "AiHubMix", limit: "10/m", blurb: "Preview build, so expect rough edges." },
    { id: "lfm-2.5-2.6b-free", provider: "AiHubMix", limit: "40/m", blurb: "2.6B. Small and fast." },
    { id: "north-mini-code-free", provider: "AiHubMix", limit: "20/m", blurb: "Cohere's North Mini for code, via AiHubMix." },
  ],
  // --- end models
};
