// OpenFlow — client config.
//
// Both values below are meant to be public. The Supabase publishable key can
// only do what your row-level security policies allow, and the resolver
// function hands back an owner ID and nothing else.
//
// Your four provider keys never appear here. They stay on your phone.

window.OPENFLOW = {
  // The live tunnel. Change this one line if the URL ever moves — every
  // sample on the site reads from here, so nothing else needs editing.
  api: "https://api-openflow.serveousercontent.com",

  supabaseUrl: "https://lellmqmqxkbiypwqbcej.supabase.co",
  supabaseKey: "sb_publishable_a6hALlGUrAM3GtbyO86cKw_fC5l71ah",

  // The model list below is the site's source of truth — the gateway is never
  // asked which models exist. Limits are PER ACCOUNT: the figure shown is what
  // each signed-in user gets, not a pool anyone shares. Set this to false and
  // the site stops contacting the gateway entirely, becoming fully static.
  liveCapacity: true,
  // --- models: generated by sitemodels.py from models.json
  models: [
    { id: "nvidia/nemotron-3-nano-30b-a3b", provider: "NVIDIA", limit: "30/m", blurb: "30B total, 3B active. The light end of the Nemotron 3 line." },
    { id: "google/diffusiongemma-26b-a4b-it", provider: "NVIDIA", limit: "20/m", blurb: "26B total, 4B active." },
    { id: "mistral-large-latest", provider: "Mistral", limit: "1/s", blurb: "Mistral's flagship. One call a second, each." },
    { id: "mistral-small-latest", provider: "Mistral", limit: "1/s", blurb: "Cheap and quick for everyday prompts." },
    { id: "mistral-medium-latest", provider: "Mistral", limit: "1/s", blurb: "Between large and small." },
    { id: "gemma-4-31b-it", provider: "Google (Gemma)", limit: "30/m", blurb: "Gemma 4, 31B. This key serves Gemma only." },
    { id: "gemma-4-26b-a4b-it", provider: "Google (Gemma)", limit: "30/m", blurb: "Gemma 4, 26B total with 4B active." },
    { id: "poolside/laguna-xs-2.1", provider: "Poolside", limit: "40/m", blurb: "Laguna XS, on Poolside's own endpoint — not sharing a key with anything else." },
    { id: "claude-haiku-4-5-20251001", provider: "ccproxy", limit: "20/m", blurb: "Haiku 4.5 via ccproxy. The only model exposed from that side." },
    { id: "google/google-paligemma", provider: "NVIDIA", limit: "30/m", blurb: "Sees images. Also the describer — send a picture to any text-only model here and this one writes what's in it first." },
    { id: "mistralai/mistral-nemotron", provider: "NVIDIA", limit: "20/m", blurb: "Mistral weights, NVIDIA's tuning." },
    { id: "nvidia/cosmos3-nano", provider: "NVIDIA", limit: "5/m", blurb: "Cosmos 3 Nano. Untested through this gateway — see the note in the provider block if it doesn't answer." },
    { id: "treyleo16/llama4:31b", provider: "Ollama", limit: "6/m", blurb: "31B, running locally. Slow to answer, so requests queue rather than bounce." },
    { id: "treyleo16/trai-4-zynr-super-lightweight", provider: "Ollama", limit: "60/m", blurb: "Lightweight local model. Quickest thing on the list." },
    { id: "gpt-oss:120b-cloud", provider: "Ollama", limit: "10/m", blurb: "Open-weight 120B, run on Ollama Cloud rather than this machine." },
    { id: "gpt-oss:20b-cloud", provider: "Ollama", limit: "20/m", blurb: "The 20B sibling. Quicker, still off-device." },
    { id: "minimax-m3:cloud", provider: "Ollama", limit: "10/m", blurb: "MiniMax M3, run on Ollama Cloud." },
    { id: "nemotron-3-ultra:cloud", provider: "Ollama", limit: "6/m", blurb: "550B total, 55B active. The heaviest here — expect a wait." },
    { id: "north-mini-code-1-0", provider: "Cohere", limit: "15/m", blurb: "Cohere North Mini, tuned for code." },
    { id: "zai/GLM-5.1", provider: "Crusoe", limit: "10/m", blurb: "GLM 5.1." },
    { id: "zai/GLM-5.2", provider: "Crusoe", limit: "10/m", blurb: "GLM 5.2." },
    { id: "deepseek-ai/Deepseek-V4-Flash", provider: "Crusoe", limit: "20/m", blurb: "DeepSeek V4, flash tier." },
    { id: "deepseek-ai/DeepSeek-V3-0324", provider: "Crusoe", limit: "10/m", blurb: "DeepSeek V3, March build." },
    { id: "deepseek-ai/DeepSeek-V4-Pro", provider: "Crusoe", limit: "6/m", blurb: "DeepSeek V4 Pro. The heavy one." },
    { id: "google/gemma-4-31b-it", provider: "Crusoe", limit: "20/m", blurb: "Gemma 4, 31B, via Crusoe." },
    { id: "meta-llama/Llama-3.3-70B-Instruct", provider: "Crusoe", limit: "15/m", blurb: "70B general-purpose." },
    { id: "moonshotai/Kimi-K2.6", provider: "Crusoe", limit: "10/m", blurb: "256K context. Built for agentic tool use." },
    { id: "nvidia/Nemotron-3-Nano-Omni-Reasoning-30B-A3B", provider: "Crusoe", limit: "20/m", blurb: "Multimodal MoE, ~3B active, 262K context. Sees images." },
    { id: "nvidia/Nemotron-3.5-Lightning-30B-A3B", provider: "Crusoe", limit: "25/m", blurb: "Lightning tier — tuned for speed." },
    { id: "nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B", provider: "Crusoe", limit: "25/m", blurb: "30B total, 3B active." },
    { id: "nvidia/NVIDIA-Nemotron-3-Super-120B-A12B", provider: "Crusoe", limit: "10/m", blurb: "120B total, 12B active." },
    { id: "Qwen/Qwen3-235B-A22B-Instruct-2507", provider: "Crusoe", limit: "8/m", blurb: "235B total, 22B active. Biggest Qwen here." },
    { id: "yutori/n1.5", provider: "Crusoe", limit: "15/m", blurb: "Yutori N1.5." },
  ],
  // --- end models
};
