// OpenFlow — client config.
//
// Both values below are meant to be public. The Supabase publishable key can
// only do what your row-level security policies allow, and the resolver
// function hands back an owner ID and nothing else.
//
// Your four provider keys never appear here. They stay on your phone.

window.OPENFLOW = {
  // The live tunnel. Change this one line if the URL ever moves — every
  // sample on the site reads from here, so nothing else needs editing.
  api: "https://api-openflow.serveousercontent.com",

  supabaseUrl: "https://lellmqmqxkbiypwqbcej.supabase.co",
  supabaseKey: "sb_publishable_a6hALlGUrAM3GtbyO86cKw_fC5l71ah",

  // The model list below is the site's source of truth — the gateway is never
  // asked which models exist. Limits are PER ACCOUNT: the figure shown is what
  // each signed-in user gets, not a pool anyone shares. Set this to false and
  // the site stops contacting the gateway entirely, becoming fully static.
  liveCapacity: true,
  // --- models: generated by sitemodels.py from models.json
  models: [
    { id: "nvidia/nemotron-3-nano-30b-a3b", provider: "NVIDIA", limit: "30/m", kind: "chat", blurb: "30B total, 3B active. The light end of the Nemotron 3 line." },
    { id: "google/diffusiongemma-26b-a4b-it", provider: "NVIDIA", limit: "20/m", kind: "chat", blurb: "26B total, 4B active." },
    { id: "mistral-large-latest", provider: "Mistral", limit: "1/s", kind: "chat", blurb: "Mistral's flagship. One call a second, each." },
    { id: "mistral-small-latest", provider: "Mistral", limit: "1/s", kind: "chat", blurb: "Cheap and quick for everyday prompts." },
    { id: "mistral-medium-latest", provider: "Mistral", limit: "1/s", kind: "chat", blurb: "Between large and small." },
    { id: "gemma-4-31b-it", provider: "Google (Gemma)", limit: "30/m", kind: "chat", blurb: "Gemma 4, 31B. This key serves Gemma only." },
    { id: "gemma-4-26b-a4b-it", provider: "Google (Gemma)", limit: "30/m", kind: "chat", blurb: "Gemma 4, 26B total with 4B active." },
    { id: "poolside/laguna-xs-2.1", provider: "Poolside", limit: "40/m", kind: "chat", blurb: "Laguna XS, on Poolside's own endpoint — not sharing a key with anything else." },
    { id: "google/google-paligemma", provider: "NVIDIA", limit: "30/m", kind: "chat", blurb: "Sees images. Also the describer — send a picture to any text-only model here and this one writes what's in it first." },
    { id: "mistralai/mistral-nemotron", provider: "NVIDIA", limit: "20/m", kind: "chat", blurb: "Mistral weights, NVIDIA's tuning." },
    { id: "treyleo16/llama4:31b", provider: "Ollama", limit: "6/m", kind: "chat", blurb: "Llama 4 at 31B." },
    { id: "treyleo16/trai-4-zynr-super-lightweight", provider: "Ollama", limit: "60/m", kind: "chat", blurb: "Lightweight — the quickest of yours." },
    { id: "gpt-oss:120b-cloud", provider: "Ollama", limit: "10/m", kind: "chat", blurb: "Open-weight 120B, run on Ollama Cloud rather than this machine." },
    { id: "gpt-oss:20b-cloud", provider: "Ollama", limit: "20/m", kind: "chat", blurb: "The 20B sibling. Quicker, still off-device." },
    { id: "minimax-m3:cloud", provider: "Ollama", limit: "10/m", kind: "chat", blurb: "MiniMax M3, run on Ollama Cloud." },
    { id: "nemotron-3-ultra:cloud", provider: "Ollama", limit: "6/m", kind: "chat", blurb: "550B total, 55B active. The heaviest here — expect a wait." },
    { id: "bjoernb/gemma4-31b-think", provider: "Ollama", limit: "6/m", kind: "chat", blurb: "Gemma 4 31B with thinking enabled." },
    { id: "YuriiFominYoung/fable-5", provider: "Ollama", limit: "10/m", kind: "chat", blurb: "Fable 5." },
    { id: "treyleo16/opus-5", provider: "Ollama", limit: "10/m", kind: "chat", blurb: "Opus 5 — Anthropic's model." },
    { id: "treyleo16/haiku-4-5", provider: "Ollama", limit: "20/m", kind: "chat", blurb: "Haiku 4.5 — Anthropic's model. Replaces the old ccproxy route." },
    { id: "treyleo16/sonnet-5", provider: "Ollama", limit: "15/m", kind: "chat", blurb: "Sonnet 5 — Anthropic's model." },
    { id: "treyleo16/gpt-5-6-sol", provider: "Ollama", limit: "15/m", kind: "chat", blurb: "GPT-5.6 Sol — OpenAI's model." },
    { id: "treyleo16/gpt-4o", provider: "Ollama", limit: "20/m", kind: "chat", blurb: "GPT-4o — OpenAI's model." },
    { id: "treyleo16/gpt-4o:mini", provider: "Ollama", limit: "30/m", kind: "chat", blurb: "GPT-4o mini — OpenAI's model." },
    { id: "treyleo16/gemini-3-1-pro", provider: "Ollama", limit: "15/m", kind: "chat", blurb: "Gemini 3.1 Pro — Google's model." },
    { id: "treyleo16/gemini-3-7-flash", provider: "Ollama", limit: "30/m", kind: "chat", blurb: "Gemini 3.7 Flash — Google's model." },
    { id: "treyleo16/grok-4-5", provider: "Ollama", limit: "15/m", kind: "chat", blurb: "Grok 4.5 — xAI's model." },
    { id: "treyleo16/kimi-k3", provider: "Ollama", limit: "15/m", kind: "chat", blurb: "Kimi K3 — Moonshot's model." },
    { id: "treyleo16/manus", provider: "Ollama", limit: "15/m", kind: "chat", blurb: "Manus." },
    { id: "treyleo16/muse-code", provider: "Ollama", limit: "20/m", kind: "chat", blurb: "Muse, tuned for code." },
    { id: "treyleo16/freeform", provider: "Ollama", limit: "20/m", kind: "chat", blurb: "Freeform — 31B, built by OpenFlow. The house model." },
    { id: "treyleo16/glm:5-3", provider: "Ollama", limit: "15/m", kind: "chat", blurb: "GLM 5.3 — Zhipu's model." },
    { id: "north-mini-code-1-0", provider: "Cohere", limit: "15/m", kind: "chat", blurb: "Cohere North Mini, tuned for code." },
    { id: "wan2.7-t2v", provider: "Model Studio", limit: "5/m", kind: "video", blurb: "Wan 2.7 text-to-video. Describe the shot and it makes it." },
  ],
  // --- end models
};
